// ─────────────────────────────────────────────────────────────────────────────
// Catálogo de producción de Sagle.
//
// Este archivo SOLO contiene los datos (sagas, juegos, taxonomía, pistas). Las
// imágenes NO van acá: se resuelven y suben a DigitalOcean Spaces con
// `build-seed-images.ts`, que genera `seed-images.json`. Luego `seed.ts` une
// ambos (datos + URLs del CDN) e inserta en la base.
//
// El frontend muestra UNA pista por idioma (busca la del idioma activo), por eso
// cada saga tiene exactamente una pista en en/es/fr. Las pistas no revelan el
// título de forma obvia.
// ─────────────────────────────────────────────────────────────────────────────

export type SeedGame = {
  title: string;
  birthYear: number;
  steamLink?: string | null;
};

export type SeedSaga = {
  title: string;
  link: string;
  hasMultiplayer: 'yes' | 'no' | 'some';
  categories: string[];
  perspectives: string[];
  artStyles: string[];
  games: SeedGame[];
  hints: { en: string; es: string; fr: string };
};

const wiki = (slug: string) => `https://en.wikipedia.org/wiki/${slug}`;

export const sagas: SeedSaga[] = [
  {
    title: 'The Legend of Zelda',
    link: wiki('The_Legend_of_Zelda'),
    hasMultiplayer: 'some',
    categories: ['Adventure', 'Action'],
    perspectives: ['Top Down', 'Third Person'],
    artStyles: ['Cartoon', 'Cel-Shaded'],
    games: [
      { title: 'The Legend of Zelda', birthYear: 1986 },
      { title: 'A Link to the Past', birthYear: 1991 },
      { title: 'Ocarina of Time', birthYear: 1998 },
      { title: 'The Wind Waker', birthYear: 2002 },
      { title: 'Breath of the Wild', birthYear: 2017 },
      { title: 'Tears of the Kingdom', birthYear: 2023 },
    ],
    hints: {
      en: 'A long-running Nintendo adventure set in a kingdom that needs saving, where a green-clad hero wields a sword and shield.',
      es: 'Una larga saga de aventuras de Nintendo ambientada en un reino que hay que salvar, con un héroe vestido de verde que empuña espada y escudo.',
      fr: "Une longue série d'aventure de Nintendo dans un royaume à sauver, avec un héros vêtu de vert maniant épée et bouclier.",
    },
  },
  {
    title: 'Super Mario',
    link: wiki('Super_Mario'),
    hasMultiplayer: 'yes',
    categories: ['Platformer', 'Adventure'],
    perspectives: ['Side Scroller', 'Third Person'],
    artStyles: ['Cartoon', '3D'],
    games: [
      { title: 'Super Mario Bros.', birthYear: 1985 },
      { title: 'Super Mario World', birthYear: 1990 },
      { title: 'Super Mario 64', birthYear: 1996 },
      { title: 'Super Mario Galaxy', birthYear: 2007 },
      { title: 'Super Mario Odyssey', birthYear: 2017 },
    ],
    hints: {
      en: 'A flagship Nintendo platformer where an Italian plumber rescues a princess from a spiky-shelled king.',
      es: 'Saga insignia de plataformas de Nintendo donde un fontanero italiano rescata a una princesa de un rey con caparazón de pinchos.',
      fr: "Série de plateforme phare de Nintendo où un plombier italien sauve une princesse d'un roi à carapace épineuse.",
    },
  },
  {
    title: 'Halo',
    link: wiki('Halo_(franchise)'),
    hasMultiplayer: 'yes',
    categories: ['Shooter', 'Action'],
    perspectives: ['First Person'],
    artStyles: ['Realistic', 'Sci-Fi'],
    games: [
      { title: 'Halo: Combat Evolved', birthYear: 2001 },
      { title: 'Halo 2', birthYear: 2004 },
      { title: 'Halo 3', birthYear: 2007 },
      { title: 'Halo: Reach', birthYear: 2010 },
      { title: 'Halo Infinite', birthYear: 2021, steamLink: 'https://store.steampowered.com/app/1240440' },
    ],
    hints: {
      en: 'A sci-fi shooter that defined a console launch, starring a green-armored super-soldier and his AI companion.',
      es: 'Shooter de ciencia ficción que definió el lanzamiento de una consola, con un supersoldado de armadura verde y su IA acompañante.',
      fr: "Un FPS de science-fiction qui a marqué le lancement d'une console, avec un super-soldat en armure verte et son IA.",
    },
  },
  {
    title: 'Final Fantasy',
    link: wiki('Final_Fantasy'),
    hasMultiplayer: 'some',
    categories: ['RPG', 'Adventure'],
    perspectives: ['Third Person', 'Top Down'],
    artStyles: ['Anime', 'Realistic'],
    games: [
      { title: 'Final Fantasy', birthYear: 1987 },
      { title: 'Final Fantasy VII', birthYear: 1997, steamLink: 'https://store.steampowered.com/app/39140' },
      { title: 'Final Fantasy X', birthYear: 2001 },
      { title: 'Final Fantasy XV', birthYear: 2016, steamLink: 'https://store.steampowered.com/app/637650' },
      { title: 'Final Fantasy XVI', birthYear: 2023 },
    ],
    hints: {
      en: 'A Square Enix JRPG series where each numbered entry tells a new story, but Chocobos, Moogles and a man named Cid always return.',
      es: 'Saga JRPG de Square Enix donde cada entrega numerada cuenta una historia nueva, pero siempre vuelven los Chocobos, los Moogles y un tal Cid.',
      fr: "Série de JRPG de Square Enix où chaque épisode raconte une nouvelle histoire, mais où reviennent toujours Chocobos, Mogs et un certain Cid.",
    },
  },
  {
    title: 'Grand Theft Auto',
    link: wiki('Grand_Theft_Auto'),
    hasMultiplayer: 'yes',
    categories: ['Action', 'Open World'],
    perspectives: ['Third Person', 'First Person'],
    artStyles: ['Realistic'],
    games: [
      { title: 'Grand Theft Auto III', birthYear: 2001 },
      { title: 'Grand Theft Auto: Vice City', birthYear: 2002 },
      { title: 'Grand Theft Auto: San Andreas', birthYear: 2004 },
      { title: 'Grand Theft Auto IV', birthYear: 2008 },
      { title: 'Grand Theft Auto V', birthYear: 2013, steamLink: 'https://store.steampowered.com/app/271590' },
    ],
    hints: {
      en: 'A Rockstar open-world series about crime in satirical versions of American cities, infamous for its chaos and radio stations.',
      es: 'Saga de mundo abierto de Rockstar sobre el crimen en versiones satíricas de ciudades estadounidenses, célebre por su caos y sus radios.',
      fr: "Série en monde ouvert de Rockstar sur le crime dans des versions satiriques de villes américaines, célèbre pour son chaos et ses radios.",
    },
  },
  {
    title: 'The Elder Scrolls',
    link: wiki('The_Elder_Scrolls'),
    hasMultiplayer: 'some',
    categories: ['RPG', 'Open World'],
    perspectives: ['First Person', 'Third Person'],
    artStyles: ['Realistic', 'Dark Fantasy'],
    games: [
      { title: 'The Elder Scrolls: Arena', birthYear: 1994 },
      { title: 'The Elder Scrolls III: Morrowind', birthYear: 2002, steamLink: 'https://store.steampowered.com/app/22320' },
      { title: 'The Elder Scrolls IV: Oblivion', birthYear: 2006 },
      { title: 'The Elder Scrolls V: Skyrim', birthYear: 2011, steamLink: 'https://store.steampowered.com/app/72850' },
    ],
    hints: {
      en: 'A Bethesda fantasy RPG series set on a single continent, where the latest chapter is full of dragons and a shout-wielding hero.',
      es: 'Saga de rol fantástico de Bethesda ambientada en un solo continente, donde el último capítulo está lleno de dragones y un héroe que grita.',
      fr: "Série de RPG fantastique de Bethesda sur un seul continent, dont le dernier opus regorge de dragons et d'un héros qui crie.",
    },
  },
  {
    title: 'Pokémon',
    link: wiki('Pok%C3%A9mon_(video_game_series)'),
    hasMultiplayer: 'some',
    categories: ['RPG', 'Adventure'],
    perspectives: ['Top Down', 'Third Person'],
    artStyles: ['Anime', 'Pixel Art'],
    games: [
      { title: 'Pokémon Red and Blue', birthYear: 1996 },
      { title: 'Pokémon Gold and Silver', birthYear: 1999 },
      { title: 'Pokémon Diamond and Pearl', birthYear: 2006 },
      { title: 'Pokémon Sword and Shield', birthYear: 2019 },
      { title: 'Pokémon Scarlet and Violet', birthYear: 2022 },
    ],
    hints: {
      en: 'A creature-collecting RPG franchise where you earn badges, and whose electric yellow mascot is one of gaming’s most famous faces.',
      es: 'Franquicia de rol de coleccionar criaturas donde ganás medallas, y cuya mascota amarilla eléctrica es una de las caras más famosas del medio.',
      fr: "Franchise de RPG de capture de créatures où l'on gagne des badges, et dont la mascotte jaune électrique est l'une des plus célèbres.",
    },
  },
  {
    title: 'God of War',
    link: wiki('God_of_War_(franchise)'),
    hasMultiplayer: 'no',
    categories: ['Action', 'Adventure', 'Hack and Slash'],
    perspectives: ['Third Person'],
    artStyles: ['Realistic'],
    games: [
      { title: 'God of War', birthYear: 2005 },
      { title: 'God of War II', birthYear: 2007 },
      { title: 'God of War III', birthYear: 2010 },
      { title: 'God of War (2018)', birthYear: 2018, steamLink: 'https://store.steampowered.com/app/1593500' },
      { title: 'God of War Ragnarök', birthYear: 2022 },
    ],
    hints: {
      en: 'A PlayStation action series about a vengeful bald warrior, first steeped in Greek myth and later in Norse legend.',
      es: 'Saga de acción de PlayStation sobre un guerrero calvo y vengativo, primero envuelto en mitología griega y luego en la nórdica.',
      fr: "Série d'action PlayStation sur un guerrier chauve et vengeur, d'abord plongé dans la mythologie grecque puis nordique.",
    },
  },
  {
    title: 'Dark Souls',
    link: wiki('Dark_Souls'),
    hasMultiplayer: 'some',
    categories: ['RPG', 'Action'],
    perspectives: ['Third Person'],
    artStyles: ['Dark Fantasy', 'Realistic'],
    games: [
      { title: 'Dark Souls', birthYear: 2011, steamLink: 'https://store.steampowered.com/app/570940' },
      { title: 'Dark Souls II', birthYear: 2014, steamLink: 'https://store.steampowered.com/app/335300' },
      { title: 'Dark Souls III', birthYear: 2016, steamLink: 'https://store.steampowered.com/app/374320' },
    ],
    hints: {
      en: 'A punishingly hard FromSoftware action RPG where bonfires are checkpoints and a grim "you died" message is your constant companion.',
      es: 'Action RPG de FromSoftware brutalmente difícil donde las hogueras son puntos de control y un sombrío "you died" es tu compañero constante.',
      fr: "Action-RPG très difficile de FromSoftware où les feux de camp font office de points de sauvegarde et un sinistre « you died » vous accompagne.",
    },
  },
  {
    title: 'Metal Gear',
    link: wiki('Metal_Gear'),
    hasMultiplayer: 'some',
    categories: ['Action', 'Stealth', 'Adventure'],
    perspectives: ['Third Person', 'Top Down'],
    artStyles: ['Realistic'],
    games: [
      { title: 'Metal Gear', birthYear: 1987 },
      { title: 'Metal Gear Solid', birthYear: 1998 },
      { title: 'Metal Gear Solid 2: Sons of Liberty', birthYear: 2001 },
      { title: 'Metal Gear Solid 3: Snake Eater', birthYear: 2004 },
      { title: 'Metal Gear Solid V: The Phantom Pain', birthYear: 2015, steamLink: 'https://store.steampowered.com/app/287700' },
    ],
    hints: {
      en: 'A Hideo Kojima stealth series with cardboard boxes, long cutscenes, giant walking weapons, and a soldier known as Snake.',
      es: 'Saga de sigilo de Hideo Kojima con cajas de cartón, cinemáticas larguísimas, armas bípedas gigantes y un soldado conocido como Snake.',
      fr: "Série d'infiltration de Hideo Kojima avec des cartons, de longues cinématiques, d'énormes armes bipèdes et un soldat surnommé Snake.",
    },
  },
  {
    title: "Assassin's Creed",
    link: wiki('Assassin%27s_Creed'),
    hasMultiplayer: 'some',
    categories: ['Action', 'Adventure', 'Open World', 'Stealth'],
    perspectives: ['Third Person'],
    artStyles: ['Realistic'],
    games: [
      { title: "Assassin's Creed", birthYear: 2007 },
      { title: "Assassin's Creed II", birthYear: 2009 },
      { title: "Assassin's Creed IV: Black Flag", birthYear: 2013 },
      { title: "Assassin's Creed Origins", birthYear: 2017 },
      { title: "Assassin's Creed Odyssey", birthYear: 2018 },
    ],
    hints: {
      en: 'A Ubisoft series about a secret war between assassins and templars, reliving ancestors’ memories through a machine called the Animus.',
      es: 'Saga de Ubisoft sobre una guerra secreta entre asesinos y templarios, reviviendo recuerdos de ancestros mediante una máquina llamada Animus.',
      fr: "Série Ubisoft sur une guerre secrète entre assassins et templiers, revivant les souvenirs d'ancêtres via une machine nommée l'Animus.",
    },
  },
  {
    title: 'Call of Duty',
    link: wiki('Call_of_Duty'),
    hasMultiplayer: 'yes',
    categories: ['Shooter', 'Action'],
    perspectives: ['First Person'],
    artStyles: ['Realistic'],
    games: [
      { title: 'Call of Duty', birthYear: 2003 },
      { title: 'Call of Duty 4: Modern Warfare', birthYear: 2007 },
      { title: 'Call of Duty: Modern Warfare 2', birthYear: 2009 },
      { title: 'Call of Duty: Black Ops', birthYear: 2010 },
      { title: 'Call of Duty: Modern Warfare (2019)', birthYear: 2019 },
    ],
    hints: {
      en: 'A blockbuster military shooter franchise releasing almost yearly, famous for its cinematic campaigns and massive online multiplayer.',
      es: 'Franquicia superventas de shooter militar que sale casi cada año, famosa por sus campañas cinematográficas y su multijugador online masivo.',
      fr: "Franchise de FPS militaire à succès sortant presque chaque année, connue pour ses campagnes cinématiques et son multijoueur en ligne massif.",
    },
  },
  {
    title: 'The Witcher',
    link: wiki('The_Witcher_(video_game_series)'),
    hasMultiplayer: 'no',
    categories: ['RPG', 'Open World', 'Action'],
    perspectives: ['Third Person'],
    artStyles: ['Realistic', 'Dark Fantasy'],
    games: [
      { title: 'The Witcher', birthYear: 2007, steamLink: 'https://store.steampowered.com/app/20900' },
      { title: 'The Witcher 2: Assassins of Kings', birthYear: 2011, steamLink: 'https://store.steampowered.com/app/20920' },
      { title: 'The Witcher 3: Wild Hunt', birthYear: 2015, steamLink: 'https://store.steampowered.com/app/292030' },
    ],
    hints: {
      en: 'A CD Projekt RED RPG based on Polish novels, starring a white-haired monster hunter for hire with cat-like eyes.',
      es: 'RPG de CD Projekt RED basado en novelas polacas, protagonizado por un cazador de monstruos a sueldo de pelo blanco y ojos felinos.',
      fr: "RPG de CD Projekt RED tiré de romans polonais, mettant en scène un chasseur de monstres aux cheveux blancs et aux yeux de chat.",
    },
  },
  {
    title: 'Resident Evil',
    link: wiki('Resident_Evil'),
    hasMultiplayer: 'some',
    categories: ['Horror', 'Action', 'Survival'],
    perspectives: ['Third Person', 'First Person', 'Fixed Camera'],
    artStyles: ['Realistic'],
    games: [
      { title: 'Resident Evil', birthYear: 1996 },
      { title: 'Resident Evil 2', birthYear: 1998 },
      { title: 'Resident Evil 4', birthYear: 2005 },
      { title: 'Resident Evil 7: Biohazard', birthYear: 2017, steamLink: 'https://store.steampowered.com/app/418370' },
      { title: 'Resident Evil Village', birthYear: 2021, steamLink: 'https://store.steampowered.com/app/1196590' },
    ],
    hints: {
      en: 'A Capcom survival-horror series built around a corporation’s viral outbreaks, zombies, and the elite agents who fight them.',
      es: 'Saga de survival horror de Capcom sobre los brotes víricos de una corporación, zombis y los agentes de élite que los enfrentan.',
      fr: "Série de survival horror de Capcom autour des épidémies virales d'une corporation, des zombies et des agents d'élite qui les combattent.",
    },
  },
  {
    title: 'Far Cry',
    link: wiki('Far_Cry'),
    hasMultiplayer: 'some',
    categories: ['Shooter', 'Open World', 'Action'],
    perspectives: ['First Person'],
    artStyles: ['Realistic'],
    games: [
      { title: 'Far Cry', birthYear: 2004 },
      { title: 'Far Cry 2', birthYear: 2008 },
      { title: 'Far Cry 3', birthYear: 2012, steamLink: 'https://store.steampowered.com/app/220240' },
      { title: 'Far Cry 5', birthYear: 2018, steamLink: 'https://store.steampowered.com/app/552520' },
    ],
    hints: {
      en: 'A Ubisoft first-person shooter series set in dangerous open worlds, each remembered for its charismatic, unhinged villain.',
      es: 'Saga de shooter en primera persona de Ubisoft ambientada en mundos abiertos peligrosos, recordada por sus villanos carismáticos y desquiciados.',
      fr: "Série de FPS d'Ubisoft dans des mondes ouverts dangereux, chaque opus marqué par son antagoniste charismatique et dérangé.",
    },
  },
  {
    title: 'Mortal Kombat',
    link: wiki('Mortal_Kombat'),
    hasMultiplayer: 'yes',
    categories: ['Fighting', 'Action'],
    perspectives: ['Side Scroller', '2D'],
    artStyles: ['Realistic'],
    games: [
      { title: 'Mortal Kombat', birthYear: 1992 },
      { title: 'Mortal Kombat II', birthYear: 1993 },
      { title: 'Mortal Kombat X', birthYear: 2015, steamLink: 'https://store.steampowered.com/app/307780' },
      { title: 'Mortal Kombat 11', birthYear: 2019, steamLink: 'https://store.steampowered.com/app/976310' },
      { title: 'Mortal Kombat 1', birthYear: 2023 },
    ],
    hints: {
      en: 'A blood-soaked fighting series infamous for its brutal finishing moves and a tournament to save the realms.',
      es: 'Saga de lucha empapada en sangre, célebre por sus brutales movimientos finales y un torneo para salvar los reinos.',
      fr: "Série de combat sanglante, tristement célèbre pour ses « finitions » brutales et un tournoi pour sauver les royaumes.",
    },
  },
  {
    title: 'Street Fighter',
    link: wiki('Street_Fighter'),
    hasMultiplayer: 'yes',
    categories: ['Fighting', 'Action'],
    perspectives: ['Side Scroller', '2D'],
    artStyles: ['Anime', 'Stylized'],
    games: [
      { title: 'Street Fighter', birthYear: 1987 },
      { title: 'Street Fighter II', birthYear: 1991 },
      { title: 'Street Fighter IV', birthYear: 2008 },
      { title: 'Street Fighter V', birthYear: 2016, steamLink: 'https://store.steampowered.com/app/310950' },
      { title: 'Street Fighter 6', birthYear: 2023, steamLink: 'https://store.steampowered.com/app/1364780' },
    ],
    hints: {
      en: 'A Capcom fighting series that popularized the genre, with a karate gi-wearing hero whose fireball and rising punch are iconic.',
      es: 'Saga de lucha de Capcom que popularizó el género, con un héroe de gi de karate cuyo proyectil de energía y puñetazo ascendente son icónicos.',
      fr: "Série de combat de Capcom qui a popularisé le genre, avec un héros en karategi dont la boule d'énergie et l'uppercut sont emblématiques.",
    },
  },
  {
    title: 'Tekken',
    link: wiki('Tekken'),
    hasMultiplayer: 'yes',
    categories: ['Fighting', 'Action'],
    perspectives: ['Third Person'],
    artStyles: ['Realistic', '3D'],
    games: [
      { title: 'Tekken', birthYear: 1994 },
      { title: 'Tekken 3', birthYear: 1997 },
      { title: 'Tekken 5', birthYear: 2004 },
      { title: 'Tekken 7', birthYear: 2015, steamLink: 'https://store.steampowered.com/app/389730' },
      { title: 'Tekken 8', birthYear: 2024, steamLink: 'https://store.steampowered.com/app/1778820' },
    ],
    hints: {
      en: 'A 3D fighting series built around a dysfunctional family feud, where rivals are literally thrown off cliffs and into volcanoes.',
      es: 'Saga de lucha en 3D centrada en la disputa de una familia disfuncional, donde los rivales son arrojados literalmente por acantilados y volcanes.',
      fr: "Série de combat en 3D centrée sur la querelle d'une famille dysfonctionnelle, où l'on jette ses rivaux du haut des falaises et dans des volcans.",
    },
  },
  {
    title: 'Sonic the Hedgehog',
    link: wiki('Sonic_the_Hedgehog'),
    hasMultiplayer: 'some',
    categories: ['Platformer', 'Action'],
    perspectives: ['Side Scroller', 'Third Person'],
    artStyles: ['Cartoon', '3D'],
    games: [
      { title: 'Sonic the Hedgehog', birthYear: 1991 },
      { title: 'Sonic the Hedgehog 2', birthYear: 1992 },
      { title: 'Sonic Adventure', birthYear: 1998 },
      { title: 'Sonic Generations', birthYear: 2011, steamLink: 'https://store.steampowered.com/app/71340' },
      { title: 'Sonic Frontiers', birthYear: 2022, steamLink: 'https://store.steampowered.com/app/1237320' },
    ],
    hints: {
      en: 'A Sega platformer about a fast blue mascot collecting golden rings while a mustached egg-shaped scientist schemes against him.',
      es: 'Plataformas de Sega sobre una veloz mascota azul que junta anillos dorados mientras un científico con bigote y forma de huevo conspira contra él.',
      fr: "Jeu de plateforme de Sega où une mascotte bleue rapide collecte des anneaux dorés tandis qu'un savant moustachu en forme d'œuf complote.",
    },
  },
  {
    title: 'Mega Man',
    link: wiki('Mega_Man'),
    hasMultiplayer: 'no',
    categories: ['Platformer', 'Action', 'Shooter'],
    perspectives: ['Side Scroller', '2D'],
    artStyles: ['Pixel Art', 'Anime'],
    games: [
      { title: 'Mega Man', birthYear: 1987 },
      { title: 'Mega Man 2', birthYear: 1988 },
      { title: 'Mega Man X', birthYear: 1993 },
      { title: 'Mega Man 11', birthYear: 2018, steamLink: 'https://store.steampowered.com/app/742300' },
    ],
    hints: {
      en: 'A Capcom action-platformer about a blue robot boy who copies the weapon of each boss he defeats.',
      es: 'Plataformas de acción de Capcom sobre un robot azul con forma de niño que copia el arma de cada jefe que derrota.',
      fr: "Jeu d'action-plateforme de Capcom sur un petit robot bleu qui copie l'arme de chaque boss qu'il vainc.",
    },
  },
  {
    title: 'Castlevania',
    link: wiki('Castlevania'),
    hasMultiplayer: 'no',
    categories: ['Platformer', 'Action', 'Metroidvania'],
    perspectives: ['Side Scroller', '2D'],
    artStyles: ['Pixel Art', 'Anime', 'Dark Fantasy'],
    games: [
      { title: 'Castlevania', birthYear: 1986 },
      { title: 'Symphony of the Night', birthYear: 1997 },
      { title: 'Aria of Sorrow', birthYear: 2003 },
    ],
    hints: {
      en: 'A Konami gothic action series about a clan of whip-wielding hunters storming a vampire lord’s ever-changing castle.',
      es: 'Saga gótica de acción de Konami sobre un clan de cazadores armados con látigos que asaltan el castillo siempre cambiante de un señor vampiro.',
      fr: "Série d'action gothique de Konami sur un clan de chasseurs au fouet prenant d'assaut le château changeant d'un seigneur vampire.",
    },
  },
  {
    title: 'Metroid',
    link: wiki('Metroid'),
    hasMultiplayer: 'no',
    categories: ['Action', 'Adventure', 'Metroidvania', 'Shooter'],
    perspectives: ['Side Scroller', 'First Person'],
    artStyles: ['Pixel Art', 'Sci-Fi', '3D'],
    games: [
      { title: 'Metroid', birthYear: 1986 },
      { title: 'Super Metroid', birthYear: 1994 },
      { title: 'Metroid Prime', birthYear: 2002 },
      { title: 'Metroid Dread', birthYear: 2021 },
    ],
    hints: {
      en: 'A Nintendo sci-fi series about a lone armored bounty hunter exploring alien worlds — and a famous twist about who she is.',
      es: 'Saga de ciencia ficción de Nintendo sobre una cazarrecompensas solitaria con armadura que explora mundos alienígenas, con un famoso giro sobre quién es.',
      fr: "Série de science-fiction de Nintendo sur une chasseuse de primes solitaire en armure explorant des mondes extraterrestres, et un fameux twist sur son identité.",
    },
  },
  {
    title: 'Tomb Raider',
    link: wiki('Tomb_Raider'),
    hasMultiplayer: 'some',
    categories: ['Action', 'Adventure'],
    perspectives: ['Third Person'],
    artStyles: ['Realistic'],
    games: [
      { title: 'Tomb Raider', birthYear: 1996 },
      { title: 'Tomb Raider II', birthYear: 1997 },
      { title: 'Tomb Raider (2013)', birthYear: 2013, steamLink: 'https://store.steampowered.com/app/203160' },
      { title: 'Rise of the Tomb Raider', birthYear: 2015, steamLink: 'https://store.steampowered.com/app/391220' },
      { title: 'Shadow of the Tomb Raider', birthYear: 2018, steamLink: 'https://store.steampowered.com/app/750920' },
    ],
    hints: {
      en: 'An action-adventure series about an athletic British archaeologist raiding ancient tombs and solving deadly puzzles.',
      es: 'Saga de acción y aventura sobre una atlética arqueóloga británica que saquea tumbas antiguas y resuelve acertijos mortales.',
      fr: "Série d'action-aventure sur une archéologue britannique athlétique qui pille des tombes anciennes et résout des énigmes mortelles.",
    },
  },
  {
    title: 'Uncharted',
    link: wiki('Uncharted'),
    hasMultiplayer: 'some',
    categories: ['Action', 'Adventure'],
    perspectives: ['Third Person'],
    artStyles: ['Realistic'],
    games: [
      { title: "Uncharted: Drake's Fortune", birthYear: 2007 },
      { title: 'Uncharted 2: Among Thieves', birthYear: 2009 },
      { title: 'Uncharted 3: Drake’s Deception', birthYear: 2011 },
      { title: 'Uncharted 4: A Thief’s End', birthYear: 2016, steamLink: 'https://store.steampowered.com/app/1659420' },
    ],
    hints: {
      en: 'A cinematic PlayStation adventure series about a wisecracking treasure hunter scaling ruins in search of lost legends.',
      es: 'Saga de aventuras cinematográfica de PlayStation sobre un cazatesoros bromista que escala ruinas en busca de leyendas perdidas.',
      fr: "Série d'aventure cinématique PlayStation sur un chasseur de trésors plein d'humour escaladant des ruines à la recherche de légendes perdues.",
    },
  },
  {
    title: 'Battlefield',
    link: wiki('Battlefield_(video_game_series)'),
    hasMultiplayer: 'yes',
    categories: ['Shooter', 'Action'],
    perspectives: ['First Person'],
    artStyles: ['Realistic'],
    games: [
      { title: 'Battlefield 1942', birthYear: 2002 },
      { title: 'Battlefield: Bad Company', birthYear: 2008 },
      { title: 'Battlefield 3', birthYear: 2011 },
      { title: 'Battlefield 1', birthYear: 2016, steamLink: 'https://store.steampowered.com/app/1238840' },
      { title: 'Battlefield V', birthYear: 2018, steamLink: 'https://store.steampowered.com/app/1238810' },
    ],
    hints: {
      en: 'An EA/DICE military shooter known for large-scale battles, vehicles, and destructible environments across many wars.',
      es: 'Shooter militar de EA/DICE conocido por sus batallas a gran escala, vehículos y escenarios destructibles a lo largo de muchas guerras.',
      fr: "FPS militaire d'EA/DICE connu pour ses batailles à grande échelle, ses véhicules et ses décors destructibles à travers de nombreuses guerres.",
    },
  },
  {
    title: 'Counter-Strike',
    link: wiki('Counter-Strike'),
    hasMultiplayer: 'yes',
    categories: ['Shooter', 'Action'],
    perspectives: ['First Person'],
    artStyles: ['Realistic'],
    games: [
      { title: 'Counter-Strike', birthYear: 2000 },
      { title: 'Counter-Strike: Source', birthYear: 2004 },
      { title: 'Counter-Strike: Global Offensive', birthYear: 2012 },
      { title: 'Counter-Strike 2', birthYear: 2023, steamLink: 'https://store.steampowered.com/app/730' },
    ],
    hints: {
      en: 'A hugely competitive team shooter where counter-terrorists and terrorists buy weapons each round and plant or defuse a bomb.',
      es: 'Shooter por equipos extremadamente competitivo donde antiterroristas y terroristas compran armas cada ronda y plantan o desactivan una bomba.',
      fr: "FPS par équipes ultra-compétitif où antiterroristes et terroristes achètent des armes à chaque manche et posent ou désamorcent une bombe.",
    },
  },
  {
    title: 'Half-Life',
    link: wiki('Half-Life_(series)'),
    hasMultiplayer: 'some',
    categories: ['Shooter', 'Action', 'Puzzle'],
    perspectives: ['First Person'],
    artStyles: ['Realistic', 'Sci-Fi'],
    games: [
      { title: 'Half-Life', birthYear: 1998, steamLink: 'https://store.steampowered.com/app/70' },
      { title: 'Half-Life 2', birthYear: 2004, steamLink: 'https://store.steampowered.com/app/220' },
      { title: 'Half-Life: Alyx', birthYear: 2020, steamLink: 'https://store.steampowered.com/app/546560' },
    ],
    hints: {
      en: 'A genre-defining Valve shooter starring a silent physicist with a crowbar and a hazard suit, resisting an alien occupation.',
      es: 'Shooter de Valve que definió el género, protagonizado por un físico silencioso con palanca y traje de protección que resiste una ocupación alienígena.',
      fr: "FPS de Valve qui a défini le genre, mettant en scène un physicien muet armé d'un pied-de-biche et d'une combinaison, résistant à une invasion extraterrestre.",
    },
  },
  {
    title: 'Portal',
    link: wiki('Portal_(series)'),
    hasMultiplayer: 'some',
    categories: ['Puzzle', 'Action'],
    perspectives: ['First Person'],
    artStyles: ['Sci-Fi', 'Stylized'],
    games: [
      { title: 'Portal', birthYear: 2007, steamLink: 'https://store.steampowered.com/app/400' },
      { title: 'Portal 2', birthYear: 2011, steamLink: 'https://store.steampowered.com/app/620' },
    ],
    hints: {
      en: 'A Valve first-person puzzle series where you fire two linked doorways to bend space, watched over by a sarcastic AI who promises cake.',
      es: 'Saga de puzles en primera persona de Valve donde disparás dos portales enlazados para doblar el espacio, vigilado por una IA sarcástica que promete pastel.',
      fr: "Série de puzzles à la première personne de Valve où l'on tire deux portails reliés pour plier l'espace, sous l'œil d'une IA sarcastique qui promet du gâteau.",
    },
  },
  {
    title: 'Borderlands',
    link: wiki('Borderlands_(series)'),
    hasMultiplayer: 'yes',
    categories: ['Shooter', 'RPG', 'Action'],
    perspectives: ['First Person'],
    artStyles: ['Cel-Shaded', 'Cartoon'],
    games: [
      { title: 'Borderlands', birthYear: 2009 },
      { title: 'Borderlands 2', birthYear: 2012, steamLink: 'https://store.steampowered.com/app/49520' },
      { title: 'Borderlands 3', birthYear: 2019, steamLink: 'https://store.steampowered.com/app/397540' },
    ],
    hints: {
      en: 'A cel-shaded "looter-shooter" on a lawless desert planet, famous for gazillions of randomized guns and a manic masked psycho.',
      es: 'Un "looter-shooter" con cel-shading en un planeta desértico sin ley, célebre por sus millones de armas aleatorias y un psicópata enmascarado y maníaco.',
      fr: "Un « looter-shooter » en cel-shading sur une planète désertique sans foi ni loi, célèbre pour ses millions d'armes aléatoires et un psychopathe masqué et déjanté.",
    },
  },
  {
    title: 'BioShock',
    link: wiki('BioShock'),
    hasMultiplayer: 'no',
    categories: ['Shooter', 'Action', 'RPG'],
    perspectives: ['First Person'],
    artStyles: ['Stylized', 'Realistic'],
    games: [
      { title: 'BioShock', birthYear: 2007, steamLink: 'https://store.steampowered.com/app/409710' },
      { title: 'BioShock 2', birthYear: 2010 },
      { title: 'BioShock Infinite', birthYear: 2013, steamLink: 'https://store.steampowered.com/app/8870' },
    ],
    hints: {
      en: 'A story-driven shooter set in fallen utopias — an underwater city and a city in the sky — where you gain powers from injectable plasmids.',
      es: 'Shooter narrativo ambientado en utopías caídas —una ciudad submarina y otra en el cielo— donde obtenés poderes mediante plásmidos inyectables.',
      fr: "FPS narratif dans des utopies déchues — une cité sous-marine et une cité dans le ciel — où l'on obtient des pouvoirs grâce à des plasmides injectables.",
    },
  },
  {
    title: 'Mass Effect',
    link: wiki('Mass_Effect'),
    hasMultiplayer: 'some',
    categories: ['RPG', 'Shooter', 'Action'],
    perspectives: ['Third Person'],
    artStyles: ['Realistic', 'Sci-Fi'],
    games: [
      { title: 'Mass Effect', birthYear: 2007 },
      { title: 'Mass Effect 2', birthYear: 2010 },
      { title: 'Mass Effect 3', birthYear: 2012 },
      { title: 'Mass Effect: Andromeda', birthYear: 2017, steamLink: 'https://store.steampowered.com/app/1238000' },
    ],
    hints: {
      en: 'A BioWare space-opera RPG where a commander recruits an alien crew and your choices carry across an entire galaxy-spanning trilogy.',
      es: 'RPG de ópera espacial de BioWare donde un comandante recluta una tripulación alienígena y tus decisiones se arrastran por toda una trilogía galáctica.',
      fr: "RPG d'opéra spatial de BioWare où un commandant recrute un équipage extraterrestre et où vos choix se répercutent sur toute une trilogie galactique.",
    },
  },
  {
    title: 'Dragon Age',
    link: wiki('Dragon_Age'),
    hasMultiplayer: 'no',
    categories: ['RPG', 'Action', 'Adventure'],
    perspectives: ['Third Person', 'Isometric'],
    artStyles: ['Realistic', 'Dark Fantasy'],
    games: [
      { title: 'Dragon Age: Origins', birthYear: 2009 },
      { title: 'Dragon Age II', birthYear: 2011 },
      { title: 'Dragon Age: Inquisition', birthYear: 2014, steamLink: 'https://store.steampowered.com/app/1222690' },
      { title: 'Dragon Age: The Veilguard', birthYear: 2024, steamLink: 'https://store.steampowered.com/app/1845910' },
    ],
    hints: {
      en: 'A BioWare dark-fantasy RPG about gathering companions to stop demonic invasions from a tear in the world called the Veil.',
      es: 'RPG de fantasía oscura de BioWare sobre reunir compañeros para frenar invasiones demoníacas surgidas de una grieta en el mundo llamada el Velo.',
      fr: "RPG de dark fantasy de BioWare où l'on rassemble des compagnons pour stopper des invasions démoniaques venues d'une faille du monde appelée le Voile.",
    },
  },
  {
    title: 'Diablo',
    link: wiki('Diablo_(series)'),
    hasMultiplayer: 'yes',
    categories: ['RPG', 'Action', 'Roguelike'],
    perspectives: ['Isometric', 'Top Down'],
    artStyles: ['Dark Fantasy', 'Realistic'],
    games: [
      { title: 'Diablo', birthYear: 1996 },
      { title: 'Diablo II', birthYear: 2000 },
      { title: 'Diablo III', birthYear: 2012 },
      { title: 'Diablo IV', birthYear: 2023 },
    ],
    hints: {
      en: 'A Blizzard isometric action-RPG about descending into hell, clicking through hordes of demons and hoarding ever-better loot.',
      es: 'Action-RPG isométrico de Blizzard sobre descender al infierno, hacer clic entre hordas de demonios y acumular botín cada vez mejor.',
      fr: "Action-RPG isométrique de Blizzard où l'on descend en enfer, cliquant à travers des hordes de démons et amassant un butin toujours meilleur.",
    },
  },
  {
    title: 'StarCraft',
    link: wiki('StarCraft'),
    hasMultiplayer: 'yes',
    categories: ['Strategy', 'Sci-Fi'],
    perspectives: ['Isometric', 'Top Down'],
    artStyles: ['Sci-Fi', 'Realistic'],
    games: [
      { title: 'StarCraft', birthYear: 1998 },
      { title: 'StarCraft: Brood War', birthYear: 1998 },
      { title: 'StarCraft II: Wings of Liberty', birthYear: 2010 },
    ],
    hints: {
      en: 'A Blizzard real-time strategy classic pitting humans, a ravenous insectoid swarm and a psychic alien race against each other.',
      es: 'Clásico de estrategia en tiempo real de Blizzard que enfrenta a humanos, un voraz enjambre insectoide y una raza alienígena psíquica.',
      fr: "Classique de la stratégie en temps réel de Blizzard opposant des humains, un essaim insectoïde vorace et une race extraterrestre psychique.",
    },
  },
  {
    title: 'Warcraft',
    link: wiki('Warcraft'),
    hasMultiplayer: 'yes',
    categories: ['Strategy', 'RPG'],
    perspectives: ['Isometric', 'Top Down', 'Third Person'],
    artStyles: ['Stylized', 'Cartoon'],
    games: [
      { title: 'Warcraft: Orcs & Humans', birthYear: 1994 },
      { title: 'Warcraft II: Tides of Darkness', birthYear: 1995 },
      { title: 'Warcraft III: Reign of Chaos', birthYear: 2002 },
      { title: 'World of Warcraft', birthYear: 2004 },
    ],
    hints: {
      en: 'A Blizzard fantasy franchise of orcs versus humans that began as strategy games and grew into a colossal online world.',
      es: 'Franquicia de fantasía de Blizzard de orcos contra humanos que empezó como juegos de estrategia y creció hasta un colosal mundo online.',
      fr: "Franchise fantastique de Blizzard d'orcs contre humains, née de jeux de stratégie et devenue un colossal monde en ligne.",
    },
  },
  {
    title: 'The Sims',
    link: wiki('The_Sims'),
    hasMultiplayer: 'no',
    categories: ['Simulation', 'Sandbox'],
    perspectives: ['Isometric', 'Third Person'],
    artStyles: ['Cartoon', 'Stylized'],
    games: [
      { title: 'The Sims', birthYear: 2000 },
      { title: 'The Sims 2', birthYear: 2004 },
      { title: 'The Sims 3', birthYear: 2009 },
      { title: 'The Sims 4', birthYear: 2014, steamLink: 'https://store.steampowered.com/app/1222670' },
    ],
    hints: {
      en: 'A best-selling life-simulation series where you build houses and guide little people who speak a gibberish language of their own.',
      es: 'Saga superventas de simulación de vida donde construís casas y guiás a personitas que hablan su propio idioma inventado.',
      fr: "Série de simulation de vie à succès où l'on construit des maisons et guide de petits personnages parlant leur propre charabia.",
    },
  },
  {
    title: 'Need for Speed',
    link: wiki('Need_for_Speed'),
    hasMultiplayer: 'yes',
    categories: ['Racing', 'Action'],
    perspectives: ['Third Person', 'First Person'],
    artStyles: ['Realistic'],
    games: [
      { title: 'The Need for Speed', birthYear: 1994 },
      { title: 'Need for Speed: Underground', birthYear: 2003 },
      { title: 'Need for Speed: Most Wanted', birthYear: 2005 },
      { title: 'Need for Speed Heat', birthYear: 2019, steamLink: 'https://store.steampowered.com/app/1222680' },
    ],
    hints: {
      en: 'An EA arcade racing series about street racing, car customization and outrunning the cops in flashy tuned vehicles.',
      es: 'Saga de carreras arcade de EA sobre picadas callejeras, tuneo de autos y escapar de la policía en vehículos llamativos.',
      fr: "Série de course arcade d'EA sur les courses de rue, la customisation de voitures et les courses-poursuites avec la police dans des bolides tunés.",
    },
  },
  {
    title: 'Gran Turismo',
    link: wiki('Gran_Turismo'),
    hasMultiplayer: 'yes',
    categories: ['Racing', 'Simulation', 'Sports'],
    perspectives: ['Third Person', 'First Person'],
    artStyles: ['Realistic'],
    games: [
      { title: 'Gran Turismo', birthYear: 1997 },
      { title: 'Gran Turismo 3: A-Spec', birthYear: 2001 },
      { title: 'Gran Turismo 5', birthYear: 2010 },
      { title: 'Gran Turismo 7', birthYear: 2022 },
    ],
    hints: {
      en: 'A PlayStation-exclusive racing simulator obsessed with realism, calling itself "The Real Driving Simulator" with hundreds of licensed cars.',
      es: 'Simulador de carreras exclusivo de PlayStation obsesionado con el realismo, autodenominado "El simulador de conducción real" con cientos de autos con licencia.',
      fr: "Simulateur de course exclusif à PlayStation obsédé par le réalisme, se présentant comme « le vrai simulateur de conduite » avec des centaines de voitures sous licence.",
    },
  },
  {
    title: 'Red Dead',
    link: wiki('Red_Dead'),
    hasMultiplayer: 'yes',
    categories: ['Action', 'Open World', 'Adventure'],
    perspectives: ['Third Person', 'First Person'],
    artStyles: ['Realistic'],
    games: [
      { title: 'Red Dead Revolver', birthYear: 2004 },
      { title: 'Red Dead Redemption', birthYear: 2010 },
      { title: 'Red Dead Redemption 2', birthYear: 2018, steamLink: 'https://store.steampowered.com/app/1174180' },
    ],
    hints: {
      en: 'A Rockstar open-world western about outlaws on horseback in the dying days of the American frontier.',
      es: 'Saga western de mundo abierto de Rockstar sobre forajidos a caballo en los últimos días de la frontera estadounidense.',
      fr: "Western en monde ouvert de Rockstar sur des hors-la-loi à cheval, au crépuscule de la frontière américaine.",
    },
  },
  {
    title: 'Crash Bandicoot',
    link: wiki('Crash_Bandicoot'),
    hasMultiplayer: 'some',
    categories: ['Platformer', 'Adventure'],
    perspectives: ['Third Person', 'Side Scroller'],
    artStyles: ['Cartoon', '3D'],
    games: [
      { title: 'Crash Bandicoot', birthYear: 1996 },
      { title: 'Crash Bandicoot 2: Cortex Strikes Back', birthYear: 1997 },
      { title: 'Crash Bandicoot: Warped', birthYear: 1998 },
      { title: "Crash Bandicoot 4: It's About Time", birthYear: 2020, steamLink: 'https://store.steampowered.com/app/1378603' },
    ],
    hints: {
      en: 'A colorful platformer about a spinning orange marsupial smashing crates on tropical islands to stop a mad scientist.',
      es: 'Plataformas colorido sobre un marsupial naranja que gira y rompe cajas en islas tropicales para frenar a un científico loco.',
      fr: "Jeu de plateforme coloré où un marsupial orange tournoyant casse des caisses sur des îles tropicales pour arrêter un savant fou.",
    },
  },
];
